CREATE TABLE tarot_cards (
    id SERIAL PRIMARY KEY,
    card_name TEXT NOT NULL,
    arcana TEXT NOT NULL,
    suit TEXT NOT NULL,
    img TEXT NOT NULL,
    companion_cards TEXT[],
    meaning TEXT NOT NULL,
    reversed_meaning TEXT NOT NULL,
    keywords TEXT[],
    questions_to_ask TEXT[],
    past TEXT NOT NULL,
    present TEXT NOT NULL,
    future TEXT NOT NULL,
    archetype TEXT NOT NULL,
    numerology INTEGER NOT NULL,
    element TEXT NOT NULL,
    color_associations TEXT NOT NULL,
    astrological_associations TEXT NOT NULL
);